name: py
on: push
jobs:
      build:
        runs-on: ubuntu-latest
  
        steps:
          - name: checkout repo content
            uses: actions/checkout@v2 # checkout the repository content to github runner.
          - name: setup python
            uses: actions/setup-python@v2
            with:
              python-version: 3.8 #install the python needed
          - name: install html.perser
            run: |
              python -m pip install html.perser
          - name: install cfscrape
            run: |
              python -m pip install cfscrape
          - name: install Pyrebase4
            run: |
              python -m pip install Pyrebase4
          - name: install request
            run: |
              python -m pip install requests
          - name: install bs4
            run: |
              python -m pip install bs4
          - name: execute py script 
            run: |
              python hmad.py
